/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface StdError extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): StdError;
  clone(): StdError;
  methods: {
    arithmeticError(): NonPayableTransactionObject<string>;

    assertionError(): NonPayableTransactionObject<string>;

    divisionError(): NonPayableTransactionObject<string>;

    encodeStorageError(): NonPayableTransactionObject<string>;

    enumConversionError(): NonPayableTransactionObject<string>;

    indexOOBError(): NonPayableTransactionObject<string>;

    memOverflowError(): NonPayableTransactionObject<string>;

    popError(): NonPayableTransactionObject<string>;

    zeroVarError(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
