/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type log = ContractEventLog<{
  0: string;
}>;
export type log_address = ContractEventLog<{
  0: string;
}>;
export type log_array_uint256_array = ContractEventLog<{
  val: string[];
  0: string[];
}>;
export type log_array_int256_array = ContractEventLog<{
  val: string[];
  0: string[];
}>;
export type log_array_address_array = ContractEventLog<{
  val: string[];
  0: string[];
}>;
export type log_bytes = ContractEventLog<{
  0: string;
}>;
export type log_bytes32 = ContractEventLog<{
  0: string;
}>;
export type log_int = ContractEventLog<{
  0: string;
}>;
export type log_named_address = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_named_array_string_uint256_array = ContractEventLog<{
  key: string;
  val: string[];
  0: string;
  1: string[];
}>;
export type log_named_array_string_int256_array = ContractEventLog<{
  key: string;
  val: string[];
  0: string;
  1: string[];
}>;
export type log_named_array_string_address_array = ContractEventLog<{
  key: string;
  val: string[];
  0: string;
  1: string[];
}>;
export type log_named_bytes = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_named_bytes32 = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_named_decimal_int = ContractEventLog<{
  key: string;
  val: string;
  decimals: string;
  0: string;
  1: string;
  2: string;
}>;
export type log_named_decimal_uint = ContractEventLog<{
  key: string;
  val: string;
  decimals: string;
  0: string;
  1: string;
  2: string;
}>;
export type log_named_int = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_named_string = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_named_uint = ContractEventLog<{
  key: string;
  val: string;
  0: string;
  1: string;
}>;
export type log_string = ContractEventLog<{
  0: string;
}>;
export type log_uint = ContractEventLog<{
  0: string;
}>;
export type logs = ContractEventLog<{
  0: string;
}>;

export interface TestContract extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): TestContract;
  clone(): TestContract;
  methods: {
    excludeArtifacts(): NonPayableTransactionObject<string[]>;

    excludeContracts(): NonPayableTransactionObject<string[]>;

    excludeSenders(): NonPayableTransactionObject<string[]>;

    failed(): NonPayableTransactionObject<boolean>;

    setUp(): NonPayableTransactionObject<void>;

    targetArtifactSelectors(): NonPayableTransactionObject<
      [string, string[]][]
    >;

    targetArtifacts(): NonPayableTransactionObject<string[]>;

    targetContracts(): NonPayableTransactionObject<string[]>;

    targetInterfaces(): NonPayableTransactionObject<[string, string[]][]>;

    targetSelectors(): NonPayableTransactionObject<[string, string[]][]>;

    targetSenders(): NonPayableTransactionObject<string[]>;

    testBar(): NonPayableTransactionObject<void>;

    testFoo(x: number | string | BN): NonPayableTransactionObject<void>;
  };
  events: {
    log(cb?: Callback<log>): EventEmitter;
    log(options?: EventOptions, cb?: Callback<log>): EventEmitter;

    log_address(cb?: Callback<log_address>): EventEmitter;
    log_address(
      options?: EventOptions,
      cb?: Callback<log_address>
    ): EventEmitter;

    "log_array(uint256[])"(
      cb?: Callback<log_array_uint256_array>
    ): EventEmitter;
    "log_array(uint256[])"(
      options?: EventOptions,
      cb?: Callback<log_array_uint256_array>
    ): EventEmitter;

    "log_array(int256[])"(cb?: Callback<log_array_int256_array>): EventEmitter;
    "log_array(int256[])"(
      options?: EventOptions,
      cb?: Callback<log_array_int256_array>
    ): EventEmitter;

    "log_array(address[])"(
      cb?: Callback<log_array_address_array>
    ): EventEmitter;
    "log_array(address[])"(
      options?: EventOptions,
      cb?: Callback<log_array_address_array>
    ): EventEmitter;

    log_bytes(cb?: Callback<log_bytes>): EventEmitter;
    log_bytes(options?: EventOptions, cb?: Callback<log_bytes>): EventEmitter;

    log_bytes32(cb?: Callback<log_bytes32>): EventEmitter;
    log_bytes32(
      options?: EventOptions,
      cb?: Callback<log_bytes32>
    ): EventEmitter;

    log_int(cb?: Callback<log_int>): EventEmitter;
    log_int(options?: EventOptions, cb?: Callback<log_int>): EventEmitter;

    log_named_address(cb?: Callback<log_named_address>): EventEmitter;
    log_named_address(
      options?: EventOptions,
      cb?: Callback<log_named_address>
    ): EventEmitter;

    "log_named_array(string,uint256[])"(
      cb?: Callback<log_named_array_string_uint256_array>
    ): EventEmitter;
    "log_named_array(string,uint256[])"(
      options?: EventOptions,
      cb?: Callback<log_named_array_string_uint256_array>
    ): EventEmitter;

    "log_named_array(string,int256[])"(
      cb?: Callback<log_named_array_string_int256_array>
    ): EventEmitter;
    "log_named_array(string,int256[])"(
      options?: EventOptions,
      cb?: Callback<log_named_array_string_int256_array>
    ): EventEmitter;

    "log_named_array(string,address[])"(
      cb?: Callback<log_named_array_string_address_array>
    ): EventEmitter;
    "log_named_array(string,address[])"(
      options?: EventOptions,
      cb?: Callback<log_named_array_string_address_array>
    ): EventEmitter;

    log_named_bytes(cb?: Callback<log_named_bytes>): EventEmitter;
    log_named_bytes(
      options?: EventOptions,
      cb?: Callback<log_named_bytes>
    ): EventEmitter;

    log_named_bytes32(cb?: Callback<log_named_bytes32>): EventEmitter;
    log_named_bytes32(
      options?: EventOptions,
      cb?: Callback<log_named_bytes32>
    ): EventEmitter;

    log_named_decimal_int(cb?: Callback<log_named_decimal_int>): EventEmitter;
    log_named_decimal_int(
      options?: EventOptions,
      cb?: Callback<log_named_decimal_int>
    ): EventEmitter;

    log_named_decimal_uint(cb?: Callback<log_named_decimal_uint>): EventEmitter;
    log_named_decimal_uint(
      options?: EventOptions,
      cb?: Callback<log_named_decimal_uint>
    ): EventEmitter;

    log_named_int(cb?: Callback<log_named_int>): EventEmitter;
    log_named_int(
      options?: EventOptions,
      cb?: Callback<log_named_int>
    ): EventEmitter;

    log_named_string(cb?: Callback<log_named_string>): EventEmitter;
    log_named_string(
      options?: EventOptions,
      cb?: Callback<log_named_string>
    ): EventEmitter;

    log_named_uint(cb?: Callback<log_named_uint>): EventEmitter;
    log_named_uint(
      options?: EventOptions,
      cb?: Callback<log_named_uint>
    ): EventEmitter;

    log_string(cb?: Callback<log_string>): EventEmitter;
    log_string(options?: EventOptions, cb?: Callback<log_string>): EventEmitter;

    log_uint(cb?: Callback<log_uint>): EventEmitter;
    log_uint(options?: EventOptions, cb?: Callback<log_uint>): EventEmitter;

    logs(cb?: Callback<logs>): EventEmitter;
    logs(options?: EventOptions, cb?: Callback<logs>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "log", cb: Callback<log>): void;
  once(event: "log", options: EventOptions, cb: Callback<log>): void;

  once(event: "log_address", cb: Callback<log_address>): void;
  once(
    event: "log_address",
    options: EventOptions,
    cb: Callback<log_address>
  ): void;

  once(event: "log_bytes", cb: Callback<log_bytes>): void;
  once(
    event: "log_bytes",
    options: EventOptions,
    cb: Callback<log_bytes>
  ): void;

  once(event: "log_bytes32", cb: Callback<log_bytes32>): void;
  once(
    event: "log_bytes32",
    options: EventOptions,
    cb: Callback<log_bytes32>
  ): void;

  once(event: "log_int", cb: Callback<log_int>): void;
  once(event: "log_int", options: EventOptions, cb: Callback<log_int>): void;

  once(event: "log_named_address", cb: Callback<log_named_address>): void;
  once(
    event: "log_named_address",
    options: EventOptions,
    cb: Callback<log_named_address>
  ): void;

  once(event: "log_named_bytes", cb: Callback<log_named_bytes>): void;
  once(
    event: "log_named_bytes",
    options: EventOptions,
    cb: Callback<log_named_bytes>
  ): void;

  once(event: "log_named_bytes32", cb: Callback<log_named_bytes32>): void;
  once(
    event: "log_named_bytes32",
    options: EventOptions,
    cb: Callback<log_named_bytes32>
  ): void;

  once(
    event: "log_named_decimal_int",
    cb: Callback<log_named_decimal_int>
  ): void;
  once(
    event: "log_named_decimal_int",
    options: EventOptions,
    cb: Callback<log_named_decimal_int>
  ): void;

  once(
    event: "log_named_decimal_uint",
    cb: Callback<log_named_decimal_uint>
  ): void;
  once(
    event: "log_named_decimal_uint",
    options: EventOptions,
    cb: Callback<log_named_decimal_uint>
  ): void;

  once(event: "log_named_int", cb: Callback<log_named_int>): void;
  once(
    event: "log_named_int",
    options: EventOptions,
    cb: Callback<log_named_int>
  ): void;

  once(event: "log_named_string", cb: Callback<log_named_string>): void;
  once(
    event: "log_named_string",
    options: EventOptions,
    cb: Callback<log_named_string>
  ): void;

  once(event: "log_named_uint", cb: Callback<log_named_uint>): void;
  once(
    event: "log_named_uint",
    options: EventOptions,
    cb: Callback<log_named_uint>
  ): void;

  once(event: "log_string", cb: Callback<log_string>): void;
  once(
    event: "log_string",
    options: EventOptions,
    cb: Callback<log_string>
  ): void;

  once(event: "log_uint", cb: Callback<log_uint>): void;
  once(event: "log_uint", options: EventOptions, cb: Callback<log_uint>): void;

  once(event: "logs", cb: Callback<logs>): void;
  once(event: "logs", options: EventOptions, cb: Callback<logs>): void;
}
