contact_links:
  - name: Questions & Support Requests
    url: https://discord.com/channels/359064931246538762/585786253992132609
    about: Ask in the dev-chat channel in LUKSO's discord server

  - name: Modify or Propose a new LSP
    url: https://github.com/lukso-network/LIPs
    about: Propose a new standard in the LIPs repository
