name: Feature|Refactor Request
description: Suggest an idea to improve the repository.
title: "[Feature-Request]: "
labels:
  - feature
body:
  - attributes:
      value: |
        Please check the [issues tab](https://github.com/lukso-network/lsp-smart-contracts/issues) to avoid duplicates.
        Make sure that you have reviewed the Contributor Guidelines.
        Thanks for taking the time to provide feedback!
    type: markdown
  - attributes:
      label: "Describe the desired feature:"
      description: Explain what the feature solves/improves.
    id: feature-request
    type: textarea
    validations:
      required: true
  - attributes:
      label: "Code example that solves the feature:"
      description: "It can be a GitHub repository/gist or a simple code snippet."
    id: reproduce
    type: textarea
