/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractTSol from "./Contract.t.sol";
export type { contractTSol };
import type * as ierc721Sol from "./IERC721.sol";
export type { ierc721Sol };
import type * as lsp2FetcherWithMulticall3TSol from "./LSP2FetcherWithMulticall3.t.sol";
export type { lsp2FetcherWithMulticall3TSol };
import type * as mockErc721Sol from "./MockERC721.sol";
export type { mockErc721Sol };
import type * as stdErrorSol from "./StdError.sol";
export type { stdErrorSol };
import type * as stdStorageSol from "./StdStorage.sol";
export type { stdStorageSol };
import type * as vmSol from "./Vm.sol";
export type { vmSol };
import type * as introspection from "./introspection";
export type { introspection };
export type { ERC165 } from "./ERC165";
export type { ERC725YCore } from "./ERC725YCore";
export type { IERC165 } from "./IERC165";
export type { IERC20 } from "./IERC20";
export type { IERC725Y } from "./IERC725Y";
export type { ILSP1UniversalReceiver } from "./ILSP1UniversalReceiver";
export type { ILSP8IdentifiableDigitalAsset } from "./ILSP8IdentifiableDigitalAsset";
export type { IMulticall3 } from "./IMulticall3";
export type { LSP2FetcherWithMulticall3 } from "./LSP2FetcherWithMulticall3";
export type { LSP4DigitalAssetMetadataCore } from "./LSP4DigitalAssetMetadataCore";
export type { LSP8IdentifiableDigitalAssetCore } from "./LSP8IdentifiableDigitalAssetCore";
export type { MockERC20 } from "./MockERC20";
export type { OwnableUnset } from "./OwnableUnset";
export type { StdAssertions } from "./StdAssertions";
export type { StdInvariant } from "./StdInvariant";
export type { Test } from "./Test";
