/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface VmSafe extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): VmSafe;
  clone(): VmSafe;
  methods: {
    accesses(target: string): NonPayableTransactionObject<{
      readSlots: string[];
      writeSlots: string[];
      0: string[];
      1: string[];
    }>;

    addr(privateKey: number | string | BN): NonPayableTransactionObject<string>;

    "assertApproxEqAbs(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbs(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbs(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbs(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbsDecimal(uint256,uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbsDecimal(int256,int256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbsDecimal(uint256,uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqAbsDecimal(int256,int256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxDelta: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRel(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRel(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRel(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRel(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRelDecimal(uint256,uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRelDecimal(uint256,uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRelDecimal(int256,int256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertApproxEqRelDecimal(int256,int256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      maxPercentDelta: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes32[],bytes32[])"(
      left: (string | number[])[],
      right: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    "assertEq(int256[],int256[],string)"(
      left: (number | string | BN)[],
      right: (number | string | BN)[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(address,address,string)"(
      left: string,
      right: string,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(string,string,string)"(
      left: string,
      right: string,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(address[],address[])"(
      left: string[],
      right: string[]
    ): NonPayableTransactionObject<void>;

    "assertEq(address[],address[],string)"(
      left: string[],
      right: string[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bool,bool,string)"(
      left: boolean,
      right: boolean,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(address,address)"(
      left: string,
      right: string
    ): NonPayableTransactionObject<void>;

    "assertEq(uint256[],uint256[],string)"(
      left: (number | string | BN)[],
      right: (number | string | BN)[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bool[],bool[])"(
      left: boolean[],
      right: boolean[]
    ): NonPayableTransactionObject<void>;

    "assertEq(int256[],int256[])"(
      left: (number | string | BN)[],
      right: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    "assertEq(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes32,bytes32)"(
      left: string | number[],
      right: string | number[]
    ): NonPayableTransactionObject<void>;

    "assertEq(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(uint256[],uint256[])"(
      left: (number | string | BN)[],
      right: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes,bytes)"(
      left: string | number[],
      right: string | number[]
    ): NonPayableTransactionObject<void>;

    "assertEq(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes32,bytes32,string)"(
      left: string | number[],
      right: string | number[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(string[],string[])"(
      left: string[],
      right: string[]
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes32[],bytes32[],string)"(
      left: (string | number[])[],
      right: (string | number[])[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes,bytes,string)"(
      left: string | number[],
      right: string | number[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bool[],bool[],string)"(
      left: boolean[],
      right: boolean[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes[],bytes[])"(
      left: (string | number[])[],
      right: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    "assertEq(string[],string[],string)"(
      left: string[],
      right: string[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(string,string)"(
      left: string,
      right: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bytes[],bytes[],string)"(
      left: (string | number[])[],
      right: (string | number[])[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEq(bool,bool)"(
      left: boolean,
      right: boolean
    ): NonPayableTransactionObject<void>;

    "assertEq(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertEqDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertEqDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertEqDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertEqDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertFalse(bool,string)"(
      condition: boolean,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertFalse(bool)"(condition: boolean): NonPayableTransactionObject<void>;

    "assertGe(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGe(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGe(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGe(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGeDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGeDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGeDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGeDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGt(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGt(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGt(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGt(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGtDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGtDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertGtDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertGtDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLe(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLe(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLe(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLe(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLeDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLeDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLeDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLeDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLt(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLt(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLt(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLt(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLtDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertLtDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLtDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertLtDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes32[],bytes32[])"(
      left: (string | number[])[],
      right: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(int256[],int256[])"(
      left: (number | string | BN)[],
      right: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bool,bool,string)"(
      left: boolean,
      right: boolean,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes[],bytes[],string)"(
      left: (string | number[])[],
      right: (string | number[])[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bool,bool)"(
      left: boolean,
      right: boolean
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bool[],bool[])"(
      left: boolean[],
      right: boolean[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes,bytes)"(
      left: string | number[],
      right: string | number[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(address[],address[])"(
      left: string[],
      right: string[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(int256,int256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(uint256[],uint256[])"(
      left: (number | string | BN)[],
      right: (number | string | BN)[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bool[],bool[],string)"(
      left: boolean[],
      right: boolean[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(string,string)"(
      left: string,
      right: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(address[],address[],string)"(
      left: string[],
      right: string[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(string,string,string)"(
      left: string,
      right: string,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(address,address,string)"(
      left: string,
      right: string,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes32,bytes32)"(
      left: string | number[],
      right: string | number[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes,bytes,string)"(
      left: string | number[],
      right: string | number[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(uint256[],uint256[],string)"(
      left: (number | string | BN)[],
      right: (number | string | BN)[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(address,address)"(
      left: string,
      right: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes32,bytes32,string)"(
      left: string | number[],
      right: string | number[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(string[],string[],string)"(
      left: string[],
      right: string[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes32[],bytes32[],string)"(
      left: (string | number[])[],
      right: (string | number[])[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(string[],string[])"(
      left: string[],
      right: string[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(int256[],int256[],string)"(
      left: (number | string | BN)[],
      right: (number | string | BN)[],
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEq(bytes[],bytes[])"(
      left: (string | number[])[],
      right: (string | number[])[]
    ): NonPayableTransactionObject<void>;

    "assertNotEq(int256,int256)"(
      left: number | string | BN,
      right: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertNotEqDecimal(int256,int256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertNotEqDecimal(int256,int256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertNotEqDecimal(uint256,uint256,uint256)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN
    ): NonPayableTransactionObject<void>;

    "assertNotEqDecimal(uint256,uint256,uint256,string)"(
      left: number | string | BN,
      right: number | string | BN,
      decimals: number | string | BN,
      error: string
    ): NonPayableTransactionObject<void>;

    "assertTrue(bool)"(condition: boolean): NonPayableTransactionObject<void>;

    "assertTrue(bool,string)"(
      condition: boolean,
      error: string
    ): NonPayableTransactionObject<void>;

    assume(condition: boolean): NonPayableTransactionObject<void>;

    "breakpoint(string)"(char: string): NonPayableTransactionObject<void>;

    "breakpoint(string,bool)"(
      char: string,
      value: boolean
    ): NonPayableTransactionObject<void>;

    "broadcast()"(): NonPayableTransactionObject<void>;

    "broadcast(address)"(signer: string): NonPayableTransactionObject<void>;

    "broadcast(uint256)"(
      privateKey: number | string | BN
    ): NonPayableTransactionObject<void>;

    closeFile(path: string): NonPayableTransactionObject<void>;

    "computeCreate2Address(bytes32,bytes32)"(
      salt: string | number[],
      initCodeHash: string | number[]
    ): NonPayableTransactionObject<string>;

    "computeCreate2Address(bytes32,bytes32,address)"(
      salt: string | number[],
      initCodeHash: string | number[],
      deployer: string
    ): NonPayableTransactionObject<string>;

    computeCreateAddress(
      deployer: string,
      nonce: number | string | BN
    ): NonPayableTransactionObject<string>;

    copyFile(from: string, to: string): NonPayableTransactionObject<string>;

    createDir(
      path: string,
      recursive: boolean
    ): NonPayableTransactionObject<void>;

    "createWallet(string)"(
      walletLabel: string
    ): NonPayableTransactionObject<[string, string, string, string]>;

    "createWallet(uint256)"(
      privateKey: number | string | BN
    ): NonPayableTransactionObject<[string, string, string, string]>;

    "createWallet(uint256,string)"(
      privateKey: number | string | BN,
      walletLabel: string
    ): NonPayableTransactionObject<[string, string, string, string]>;

    "deriveKey(string,string,uint32,string)"(
      mnemonic: string,
      derivationPath: string,
      index: number | string | BN,
      language: string
    ): NonPayableTransactionObject<string>;

    "deriveKey(string,uint32,string)"(
      mnemonic: string,
      index: number | string | BN,
      language: string
    ): NonPayableTransactionObject<string>;

    "deriveKey(string,uint32)"(
      mnemonic: string,
      index: number | string | BN
    ): NonPayableTransactionObject<string>;

    "deriveKey(string,string,uint32)"(
      mnemonic: string,
      derivationPath: string,
      index: number | string | BN
    ): NonPayableTransactionObject<string>;

    "envAddress(string)"(name: string): NonPayableTransactionObject<string>;

    "envAddress(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    "envBool(string)"(name: string): NonPayableTransactionObject<boolean>;

    "envBool(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<boolean[]>;

    "envBytes(string)"(name: string): NonPayableTransactionObject<string>;

    "envBytes(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    "envBytes32(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    "envBytes32(string)"(name: string): NonPayableTransactionObject<string>;

    "envInt(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    "envInt(string)"(name: string): NonPayableTransactionObject<string>;

    "envOr(string,string,bytes32[])"(
      name: string,
      delim: string,
      defaultValue: (string | number[])[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,string,int256[])"(
      name: string,
      delim: string,
      defaultValue: (number | string | BN)[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,bool)"(
      name: string,
      defaultValue: boolean
    ): NonPayableTransactionObject<boolean>;

    "envOr(string,address)"(
      name: string,
      defaultValue: string
    ): NonPayableTransactionObject<string>;

    "envOr(string,uint256)"(
      name: string,
      defaultValue: number | string | BN
    ): NonPayableTransactionObject<string>;

    "envOr(string,string,bytes[])"(
      name: string,
      delim: string,
      defaultValue: (string | number[])[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,string,uint256[])"(
      name: string,
      delim: string,
      defaultValue: (number | string | BN)[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,string,string[])"(
      name: string,
      delim: string,
      defaultValue: string[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,bytes)"(
      name: string,
      defaultValue: string | number[]
    ): NonPayableTransactionObject<string>;

    "envOr(string,bytes32)"(
      name: string,
      defaultValue: string | number[]
    ): NonPayableTransactionObject<string>;

    "envOr(string,int256)"(
      name: string,
      defaultValue: number | string | BN
    ): NonPayableTransactionObject<string>;

    "envOr(string,string,address[])"(
      name: string,
      delim: string,
      defaultValue: string[]
    ): NonPayableTransactionObject<string[]>;

    "envOr(string,string)"(
      name: string,
      defaultValue: string
    ): NonPayableTransactionObject<string>;

    "envOr(string,string,bool[])"(
      name: string,
      delim: string,
      defaultValue: boolean[]
    ): NonPayableTransactionObject<boolean[]>;

    "envString(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    "envString(string)"(name: string): NonPayableTransactionObject<string>;

    "envUint(string)"(name: string): NonPayableTransactionObject<string>;

    "envUint(string,string)"(
      name: string,
      delim: string
    ): NonPayableTransactionObject<string[]>;

    eth_getLogs(
      fromBlock: number | string | BN,
      toBlock: number | string | BN,
      target: string,
      topics: (string | number[])[]
    ): NonPayableTransactionObject<
      [
        string,
        string[],
        string,
        string,
        string,
        string,
        string,
        string,
        boolean
      ][]
    >;

    exists(path: string): NonPayableTransactionObject<boolean>;

    ffi(commandInput: string[]): NonPayableTransactionObject<string>;

    fsMetadata(
      path: string
    ): NonPayableTransactionObject<
      [boolean, boolean, string, boolean, string, string, string]
    >;

    getBlockNumber(): NonPayableTransactionObject<string>;

    getBlockTimestamp(): NonPayableTransactionObject<string>;

    getCode(artifactPath: string): NonPayableTransactionObject<string>;

    getDeployedCode(artifactPath: string): NonPayableTransactionObject<string>;

    getLabel(account: string): NonPayableTransactionObject<string>;

    getMappingKeyAndParentOf(
      target: string,
      elementSlot: string | number[]
    ): NonPayableTransactionObject<{
      found: boolean;
      key: string;
      parent: string;
      0: boolean;
      1: string;
      2: string;
    }>;

    getMappingLength(
      target: string,
      mappingSlot: string | number[]
    ): NonPayableTransactionObject<string>;

    getMappingSlotAt(
      target: string,
      mappingSlot: string | number[],
      idx: number | string | BN
    ): NonPayableTransactionObject<string>;

    "getNonce(address)"(account: string): NonPayableTransactionObject<string>;

    "getNonce((address,uint256,uint256,uint256))"(
      wallet: [
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ]
    ): NonPayableTransactionObject<string>;

    getRecordedLogs(): NonPayableTransactionObject<
      [string[], string, string][]
    >;

    isDir(path: string): NonPayableTransactionObject<boolean>;

    isFile(path: string): NonPayableTransactionObject<boolean>;

    keyExists(json: string, key: string): NonPayableTransactionObject<boolean>;

    keyExistsJson(
      json: string,
      key: string
    ): NonPayableTransactionObject<boolean>;

    keyExistsToml(
      toml: string,
      key: string
    ): NonPayableTransactionObject<boolean>;

    label(account: string, newLabel: string): NonPayableTransactionObject<void>;

    load(
      target: string,
      slot: string | number[]
    ): NonPayableTransactionObject<string>;

    parseAddress(stringifiedValue: string): NonPayableTransactionObject<string>;

    parseBool(stringifiedValue: string): NonPayableTransactionObject<boolean>;

    parseBytes(stringifiedValue: string): NonPayableTransactionObject<string>;

    parseBytes32(stringifiedValue: string): NonPayableTransactionObject<string>;

    parseInt(stringifiedValue: string): NonPayableTransactionObject<string>;

    "parseJson(string)"(json: string): NonPayableTransactionObject<string>;

    "parseJson(string,string)"(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonAddress(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonAddressArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonBool(
      json: string,
      key: string
    ): NonPayableTransactionObject<boolean>;

    parseJsonBoolArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<boolean[]>;

    parseJsonBytes(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonBytes32(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonBytes32Array(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonBytesArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonInt(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonIntArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonKeys(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonString(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonStringArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseJsonUint(
      json: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseJsonUintArray(
      json: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    "parseToml(string,string)"(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    "parseToml(string)"(toml: string): NonPayableTransactionObject<string>;

    parseTomlAddress(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlAddressArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlBool(
      toml: string,
      key: string
    ): NonPayableTransactionObject<boolean>;

    parseTomlBoolArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<boolean[]>;

    parseTomlBytes(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlBytes32(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlBytes32Array(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlBytesArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlInt(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlIntArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlKeys(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlString(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlStringArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseTomlUint(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string>;

    parseTomlUintArray(
      toml: string,
      key: string
    ): NonPayableTransactionObject<string[]>;

    parseUint(stringifiedValue: string): NonPayableTransactionObject<string>;

    pauseGasMetering(): NonPayableTransactionObject<void>;

    projectRoot(): NonPayableTransactionObject<string>;

    "readDir(string,uint64)"(
      path: string,
      maxDepth: number | string | BN
    ): NonPayableTransactionObject<
      [string, string, string, boolean, boolean][]
    >;

    "readDir(string,uint64,bool)"(
      path: string,
      maxDepth: number | string | BN,
      followLinks: boolean
    ): NonPayableTransactionObject<
      [string, string, string, boolean, boolean][]
    >;

    "readDir(string)"(
      path: string
    ): NonPayableTransactionObject<
      [string, string, string, boolean, boolean][]
    >;

    readFile(path: string): NonPayableTransactionObject<string>;

    readFileBinary(path: string): NonPayableTransactionObject<string>;

    readLine(path: string): NonPayableTransactionObject<string>;

    readLink(linkPath: string): NonPayableTransactionObject<string>;

    record(): NonPayableTransactionObject<void>;

    recordLogs(): NonPayableTransactionObject<void>;

    rememberKey(
      privateKey: number | string | BN
    ): NonPayableTransactionObject<string>;

    removeDir(
      path: string,
      recursive: boolean
    ): NonPayableTransactionObject<void>;

    removeFile(path: string): NonPayableTransactionObject<void>;

    replace(
      input: string,
      from: string,
      to: string
    ): NonPayableTransactionObject<string>;

    resumeGasMetering(): NonPayableTransactionObject<void>;

    rpc(method: string, params: string): NonPayableTransactionObject<string>;

    rpcUrl(rpcAlias: string): NonPayableTransactionObject<string>;

    rpcUrlStructs(): NonPayableTransactionObject<[string, string][]>;

    rpcUrls(): NonPayableTransactionObject<string[][]>;

    "serializeAddress(string,string,address[])"(
      objectKey: string,
      valueKey: string,
      values: string[]
    ): NonPayableTransactionObject<string>;

    "serializeAddress(string,string,address)"(
      objectKey: string,
      valueKey: string,
      value: string
    ): NonPayableTransactionObject<string>;

    "serializeBool(string,string,bool[])"(
      objectKey: string,
      valueKey: string,
      values: boolean[]
    ): NonPayableTransactionObject<string>;

    "serializeBool(string,string,bool)"(
      objectKey: string,
      valueKey: string,
      value: boolean
    ): NonPayableTransactionObject<string>;

    "serializeBytes(string,string,bytes[])"(
      objectKey: string,
      valueKey: string,
      values: (string | number[])[]
    ): NonPayableTransactionObject<string>;

    "serializeBytes(string,string,bytes)"(
      objectKey: string,
      valueKey: string,
      value: string | number[]
    ): NonPayableTransactionObject<string>;

    "serializeBytes32(string,string,bytes32[])"(
      objectKey: string,
      valueKey: string,
      values: (string | number[])[]
    ): NonPayableTransactionObject<string>;

    "serializeBytes32(string,string,bytes32)"(
      objectKey: string,
      valueKey: string,
      value: string | number[]
    ): NonPayableTransactionObject<string>;

    "serializeInt(string,string,int256)"(
      objectKey: string,
      valueKey: string,
      value: number | string | BN
    ): NonPayableTransactionObject<string>;

    "serializeInt(string,string,int256[])"(
      objectKey: string,
      valueKey: string,
      values: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    serializeJson(
      objectKey: string,
      value: string
    ): NonPayableTransactionObject<string>;

    "serializeString(string,string,string[])"(
      objectKey: string,
      valueKey: string,
      values: string[]
    ): NonPayableTransactionObject<string>;

    "serializeString(string,string,string)"(
      objectKey: string,
      valueKey: string,
      value: string
    ): NonPayableTransactionObject<string>;

    "serializeUint(string,string,uint256)"(
      objectKey: string,
      valueKey: string,
      value: number | string | BN
    ): NonPayableTransactionObject<string>;

    "serializeUint(string,string,uint256[])"(
      objectKey: string,
      valueKey: string,
      values: (number | string | BN)[]
    ): NonPayableTransactionObject<string>;

    setEnv(name: string, value: string): NonPayableTransactionObject<void>;

    "sign((address,uint256,uint256,uint256),bytes32)"(
      wallet: [
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN
      ],
      digest: string | number[]
    ): NonPayableTransactionObject<{
      v: string;
      r: string;
      s: string;
      0: string;
      1: string;
      2: string;
    }>;

    "sign(uint256,bytes32)"(
      privateKey: number | string | BN,
      digest: string | number[]
    ): NonPayableTransactionObject<{
      v: string;
      r: string;
      s: string;
      0: string;
      1: string;
      2: string;
    }>;

    signP256(
      privateKey: number | string | BN,
      digest: string | number[]
    ): NonPayableTransactionObject<{
      r: string;
      s: string;
      0: string;
      1: string;
    }>;

    sleep(duration: number | string | BN): NonPayableTransactionObject<void>;

    split(
      input: string,
      delimiter: string
    ): NonPayableTransactionObject<string[]>;

    "startBroadcast()"(): NonPayableTransactionObject<void>;

    "startBroadcast(address)"(
      signer: string
    ): NonPayableTransactionObject<void>;

    "startBroadcast(uint256)"(
      privateKey: number | string | BN
    ): NonPayableTransactionObject<void>;

    startMappingRecording(): NonPayableTransactionObject<void>;

    startStateDiffRecording(): NonPayableTransactionObject<void>;

    stopAndReturnStateDiff(): NonPayableTransactionObject<
      [
        [string, string],
        string,
        string,
        string,
        boolean,
        string,
        string,
        string,
        string,
        string,
        boolean,
        [string, string, boolean, string, string, boolean][],
        string
      ][]
    >;

    stopBroadcast(): NonPayableTransactionObject<void>;

    stopMappingRecording(): NonPayableTransactionObject<void>;

    "toBase64(string)"(data: string): NonPayableTransactionObject<string>;

    "toBase64(bytes)"(
      data: string | number[]
    ): NonPayableTransactionObject<string>;

    "toBase64URL(string)"(data: string): NonPayableTransactionObject<string>;

    "toBase64URL(bytes)"(
      data: string | number[]
    ): NonPayableTransactionObject<string>;

    toLowercase(input: string): NonPayableTransactionObject<string>;

    "toString(address)"(value: string): NonPayableTransactionObject<string>;

    "toString(uint256)"(
      value: number | string | BN
    ): NonPayableTransactionObject<string>;

    "toString(bytes)"(
      value: string | number[]
    ): NonPayableTransactionObject<string>;

    "toString(bool)"(value: boolean): NonPayableTransactionObject<string>;

    "toString(int256)"(
      value: number | string | BN
    ): NonPayableTransactionObject<string>;

    "toString(bytes32)"(
      value: string | number[]
    ): NonPayableTransactionObject<string>;

    toUppercase(input: string): NonPayableTransactionObject<string>;

    trim(input: string): NonPayableTransactionObject<string>;

    tryFfi(
      commandInput: string[]
    ): NonPayableTransactionObject<[string, string, string]>;

    unixTime(): NonPayableTransactionObject<string>;

    writeFile(path: string, data: string): NonPayableTransactionObject<void>;

    writeFileBinary(
      path: string,
      data: string | number[]
    ): NonPayableTransactionObject<void>;

    "writeJson(string,string,string)"(
      json: string,
      path: string,
      valueKey: string
    ): NonPayableTransactionObject<void>;

    "writeJson(string,string)"(
      json: string,
      path: string
    ): NonPayableTransactionObject<void>;

    writeLine(path: string, data: string): NonPayableTransactionObject<void>;

    "writeToml(string,string,string)"(
      json: string,
      path: string,
      valueKey: string
    ): NonPayableTransactionObject<void>;

    "writeToml(string,string)"(
      json: string,
      path: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
