/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "../types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type SlotFound = ContractEventLog<{
  who: string;
  fsig: string;
  keysHash: string;
  slot: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type WARNING_UninitedSlot = ContractEventLog<{
  who: string;
  slot: string;
  0: string;
  1: string;
}>;

export interface StdStorageSafe extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): StdStorageSafe;
  clone(): StdStorageSafe;
  methods: {};
  events: {
    SlotFound(cb?: Callback<SlotFound>): EventEmitter;
    SlotFound(options?: EventOptions, cb?: Callback<SlotFound>): EventEmitter;

    WARNING_UninitedSlot(cb?: Callback<WARNING_UninitedSlot>): EventEmitter;
    WARNING_UninitedSlot(
      options?: EventOptions,
      cb?: Callback<WARNING_UninitedSlot>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "SlotFound", cb: Callback<SlotFound>): void;
  once(
    event: "SlotFound",
    options: EventOptions,
    cb: Callback<SlotFound>
  ): void;

  once(event: "WARNING_UninitedSlot", cb: Callback<WARNING_UninitedSlot>): void;
  once(
    event: "WARNING_UninitedSlot",
    options: EventOptions,
    cb: Callback<WARNING_UninitedSlot>
  ): void;
}
